### ISSUE TITLE
Post CRDs in YAML manifest to repository

### ISSUE THREAD

**Issue by onedr0p** [brennerm/uptimerobot-operator#25]
👋🏼 It would be cool if you could post the CRDs as YAML to this repo. I am assuming that they are created by kopf when the operator is deployed. 

This is kind of an issue when you want to bootstrap a cluster and the CRDs are not present before Flux gets to installed uptimerobot-operator and your manifests for monitoring. It's kind of a chicken and egg situation. Flux will try to install the custom uroperator manifests but not see any CRDs because uptimerobot-operator is not installed quite yet.

I would like to apply the CRDs in a way that forces them to exist before the uptimerobot-operator and my manifests are installed.

Thanks!

**Comment by brennerm** [comment]
Hey @onedr0p, your assumption is correct. Will work on a solution during the next days. :+1:

**Comment by onedr0p** [comment]
@brennerm any update on this? Thanks!

**Comment by tuxpeople** [comment]
+1 as I'm also running into this issue:

```
NAMESPACE       NAME       READY   MESSAGE                                                                                                                                                         REVISION               SUSPENDED
flux-system     apps       False   UptimeRobotMonitor/apps/changedetection dry-run failed, error: no matches for kind "UptimeRobotMonitor" in version "uroperator.brennerm.github.io/v1beta1"                             False
```

**Comment by tuxpeople** [comment]
Stil an issue... ;-)

**Comment by onedr0p** [comment]
Unfortunately this project appears dead. Closing this issue.
