### ISSUE TITLE
Docs: More examples / better explanation of fields in CRDs

### ISSUE THREAD

**Issue by onedr0p** [brennerm/uptimerobot-operator#26]
For example in the `UptimeRobotMonitor` CRD the field `alertContacts` is a string... what should go here? I ran the curl request to get my monitors and it returns a JSON object, do I use `id`, `friendlyName` or the full object?

```shell
curl -X POST \
  -H "Cache-Control: no-cache" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d 'api_key=<redacted>&format=json' \
"https://api.uptimerobot.com/v2/getAlertContacts"
```

```json
{
  "stat": "ok",
  "offset": 0,
  "limit": 50,
  "total": 3,
  "alert_contacts": [
    {
      "id": "<redacted>",
      "friendly_name": "<redacted>@gmail.com",
      "type": 2,
      "status": 1,
      "value": "<redacted>@gmail.com"
    },
    {
      "id": "<redacted>",
      "friendly_name": "Discord",
      "type": 11,
      "status": 2,
      "value": "https://discord.com/api/webhooks/<redacted>/slack"
    },
    {
      "id": "<redacted>",
      "friendly_name": "Phone",
      "type": 13,
      "status": 2
    }
  ]
}
```

This is pretty vague for the other fields too, not just `alertContacts`.

**Comment by brennerm** [comment]
I usually try to add a proper description for each field of the CRDs. To access it use `kubectl explain`. For your particular case it would be `kubectl explain uptimerobotmonitors.spec.alertContacts`. Does that solve your problem?

**Comment by onedr0p** [comment]
Not really, this is what is in the docs already... what is `<string>`? Is it supposed to be the value of `id`, `friendly_name`, full json object or?

```
❯ kubectl explain uptimerobotmonitors.spec.alertContacts
KIND:     UptimeRobotMonitor
VERSION:  uroperator.brennerm.github.io/v1beta1

FIELD:    alertContacts <string>

DESCRIPTION:
     Alert contacts to be notified when monitor goes up or down. For syntax
     check https://uptimerobot.com/api/#newMonitorWrap
```

**Comment by brennerm** [comment]
Think the docs explain the required value pretty good, don't they?

> optional (the alert contacts to be notified when the monitor goes up/down.Multiple alert_contact>ids can be sent like alert_contacts=457_0_0-373_5_0-8956_2_3 where alert_contact>ids are seperated with - and threshold + recurrence are seperated with _. For ex: alert_contacts=457_5_0 refers to 457 being the alert_contact>id, 5 being the threshold and 0 being the recurrence. As the threshold and recurrence is only available in the Pro Plan, they are always 0 in the Free Plan)

That's what you need to pass to the alertContacts CRD field.

**Comment by onedr0p** [comment]
Ohhh ok I see now. I think the confusing I had is that when you click that link https://uptimerobot.com/api/#newMonitorWrap it does not expand the item, nor bring to the right location on the page, poor UX on their end.

However I think the docs could be improved to say something like 

> Value of `alert_contacts` from the `newMonitor` POST method at https://uptimerobot.com/api/

**Comment by onedr0p** [comment]
Here's what I see when I click https://uptimerobot.com/api/#newMonitorWrap

![image](https://user-images.githubusercontent.com/213795/116817895-a3d28a80-ab36-11eb-9790-944a45bf5e58.png)

Silly Chrome or UptimeRobot Docs 😆

**Comment by brennerm** [comment]
Yeah unfortunately they don't have anchor links for each individual field.
