### ISSUE TITLE
Multiple architecture Docker image

### ISSUE THREAD

**Issue by onedr0p** [brennerm/uptimerobot-operator#27]
I was reviewing your Github workflow and I see you are not building multi-arch images. It's pretty easy to do using the following Github actions:

- https://github.com/docker/setup-qemu-action
- https://github.com/docker/setup-buildx-action

I can try to open a PR if you want :)

**Comment by brennerm** [comment]
Sure, feel free to submit a PR and I'll be there to review it. :+1:

**Comment by tuxpeople** [comment]
PR about to be sent ;-)

**Comment by tuxpeople** [comment]
@onedr0p until this is merged, feel free to use this image: `ghcr.io/tuxpeople/uptimerobot-operator:master`.

**Comment by onedr0p** [comment]
Unfortunately this project appears dead. Closing this issue.
